language: python
python:
  - 3.6
before_install:
  - openssl aes-256-cbc -K $encrypted_bd0c72cd4f20_key -iv $encrypted_bd0c72cd4f20_iv -in credentials.yml.enc -out credentials.yml -d
install:
  - pip install pipenv
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv install --dev
script:
  - pipenv run pytest
after_success:
  - pipenv run coveralls

# deploy:
#   provider: pypi
#   user: "nens"
#   password:
#     secure: LongStringThatNeedsToBeSetByReinout
#   # (travis encrypt NENS-PASSWORD --com --add deploy.password)
#   on:
#     tags: true
#   distributions: "sdist bdist_wheel"
#   skip_existing: true
