language: python
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_bd0c72cd4f20_key -iv $encrypted_bd0c72cd4f20_iv
  -in credentials.yml.enc -out credentials.yml -d
install:
- pip install pipenv
- PIPENV_IGNORE_VIRTUALENVS=1 pipenv install --dev
script:
- pipenv run pytest
after_success:
- pipenv run coveralls
deploy:
  provider: pypi
  user: nens
  password:
    secure: LoOyeOfnkmq99EY/qzRpCV6u+4aSvWzz8GQArWesmwFYW/ouYLk2cSCbWrk8cH/D/kkSvCoLDEvmqud1vrLAoja6RtOWrmvVh6GxtNizx8hKRRi6znEoZrVVhjE0zh+j8SjiGEYQ+fvuhEyr73K8ml2EaeeAz/5ixa8dtA8hDF/XmFOv3gROulpwRVmRombJCR9P5/84IRsz4sfAWTBderVgtWXvdanmFFe9IFiEaa+YRQpzdcf3mysq5qNoHIA/q3+AHyrlyk8ue9+kjGv3pkIwDUEgogcfq4c/KPptIhIS5jne0Z3IE5fp5VdpkIh1YrQjH2rPOoRlpJQrjNsZtiuNfcK0pTmcw5dsxmL8Xd7v8WXXh3Wq6zVJTRdzQQ8k9V02e26k2NJ0jNSbDlLymBK+lH6f1zFsN/XdFtZ5G/xCqZkOe2sE66zjDyLxWd1eyfuUPP6GlTjAHnm1twshb3rNf6Z8SVaM6WHqUlTquE0n3PMC205d1HHpsELlXdvy4MfPZfbK2q+2jN04+XZqJisGhfnDeX8zcT3wtqwcUhBMqN7ZG25XmQoXAfOnL2HFLIPp4nWUYVmXWA5j5eVBHCb3JLmANK+tJpJvLzuXK1eh1AUnpk6iEOaZ9CeR7TBs41yaY0gL+AikKvbt+Typfopzgf+Zc3aEnVTVMB54MHs=
